apiVersion: v1
kind: Service
metadata:
  name: mini-metrics
  namespace: kube-system
  labels:
    k8s-app: mini-metrics
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    k8s-app: mini-metrics
  ports:
  - name: http
    port: 8080
    protocol: TCP

